/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.3 at Mon Aug 05 22:55:45 2019. */

#include "SaveOnServer.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t SaveOnServer_fields[4] = {
    PB_FIELD(  1, STRING  , SINGULAR, CALLBACK, FIRST, SaveOnServer, device_id_mac, device_id_mac, 0),
    PB_FIELD(  2, INT32   , SINGULAR, STATIC  , OTHER, SaveOnServer, group_id, device_id_mac, 0),
    PB_FIELD(  3, INT32   , SINGULAR, STATIC  , OTHER, SaveOnServer, device_type, group_id, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
