/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.3 at Mon Aug 12 22:32:44 2019. */

#ifndef PB_BLEMESSAGE_PB_H_INCLUDED
#define PB_BLEMESSAGE_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _BleMessage {
    int32_t op;
    char mac_address[30];
    char wifiSsid[80];
    char password[80];
/* @@protoc_insertion_point(struct:BleMessage) */
} BleMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define BleMessage_init_default                  {0, "", "", ""}
#define BleMessage_init_zero                     {0, "", "", ""}

/* Field tags (for use in manual encoding/decoding) */
#define BleMessage_op_tag                        1
#define BleMessage_mac_address_tag               2
#define BleMessage_wifiSsid_tag                  3
#define BleMessage_password_tag                  4

/* Struct field encoding specification for nanopb */
extern const pb_field_t BleMessage_fields[5];

/* Maximum encoded size of messages (where known) */
#define BleMessage_size                          207

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define BLEMESSAGE_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
